import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@components/Footer/Footer";
import { Navigation } from "@components/Navigation/Navigation";

const inter = Inter({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    siteName: "Tutorial",
    description: "Tutorial for Next JS"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru" className={inter.variable}>
      <body>
        <div className="bg-grid"></div>
        <Navigation />
        <main className="container page">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
